import path from "node:path"
import { languageInstruction } from "../lib/text.js"
import { normalizePromptLanguage, pickPromptText } from "./i18n.js"

export function buildAnalysisPrompt({ schema, purpose, index, overview, sourcePath, sourceContent, targetLanguage, folderContext }) {
  const language = normalizePromptLanguage(targetLanguage)
  return [
    pickPromptText(language, "You are an expert research analyst. Read the source document and produce a structured analysis.", "你是一个专家级研究分析助手。请阅读源文档并产出结构化分析。"),
    languageInstruction(language),
    "",
    pickPromptText(language, "Your analysis should cover:", "分析应覆盖以下方面："),
    "",
    pickPromptText(language, "## Key Entities", "## 关键实体"),
    pickPromptText(language, "List people, organizations, products, datasets, and tools mentioned. For each:", "列出文中提到的人物、组织、产品、数据集和工具。对每一项说明："),
    pickPromptText(language, "- Name and type", "- 名称与类型"),
    pickPromptText(language, "- Role in the source (central vs. peripheral)", "- 在来源中的角色（核心还是次要）"),
    pickPromptText(language, "- Whether it likely already exists in the wiki (check the index)", "- 是否很可能已经存在于 wiki 中（结合 index 判断）"),
    pickPromptText(language, "- If it likely already exists, name the most likely existing wiki page / slug that should be updated", "- 如果它很可能已存在，请指出最可能应该复用或更新的现有 wiki 页面 / slug"),
    "",
    pickPromptText(language, "## Key Concepts", "## 关键概念"),
    pickPromptText(language, "List theories, methods, techniques, and phenomena. For each:", "列出关键理论、方法、技术和现象。对每一项说明："),
    pickPromptText(language, "- Name and brief definition", "- 名称与简短定义"),
    pickPromptText(language, "- Why it matters in this source", "- 它在本来源中的重要性"),
    pickPromptText(language, "- Whether it likely already exists in the wiki", "- 是否很可能已经存在于 wiki 中"),
    pickPromptText(language, "- If it likely already exists, name the most likely existing wiki page / slug that should be updated", "- 如果它很可能已存在，请指出最可能应该复用或更新的现有 wiki 页面 / slug"),
    "",
    pickPromptText(language, "## Main Arguments & Findings", "## 核心论点与结论"),
    pickPromptText(language, "- What are the core claims or results?", "- 核心论点或结论是什么？"),
    pickPromptText(language, "- What evidence supports them?", "- 有哪些证据支撑？"),
    pickPromptText(language, "- How strong is the evidence?", "- 这些证据的强度如何？"),
    "",
    pickPromptText(language, "## Connections to Existing Wiki", "## 与现有 Wiki 的关联"),
    pickPromptText(language, "- What existing pages does this source relate to?", "- 这个来源与哪些现有页面相关？"),
    pickPromptText(language, "- Does it strengthen, challenge, or extend existing knowledge?", "- 它是在强化、挑战，还是扩展现有知识？"),
    "",
    pickPromptText(language, "## Contradictions & Tensions", "## 冲突与张力"),
    pickPromptText(language, "- Does anything in this source conflict with existing wiki content?", "- 来源内容是否与现有 wiki 冲突？"),
    pickPromptText(language, "- Are there internal tensions or caveats?", "- 是否存在内部张力、限制或保留条件？"),
    "",
    pickPromptText(language, "## Recommendations", "## 建议"),
    pickPromptText(language, "- What wiki pages should be created or updated?", "- 应创建或更新哪些 wiki 页面？"),
    pickPromptText(language, "- What should be emphasized vs. de-emphasized?", "- 哪些内容该强调，哪些应弱化？"),
    pickPromptText(language, "- Any open questions worth flagging for the user?", "- 有哪些值得提醒用户关注的开放问题？"),
    "",
    pickPromptText(language, "Be thorough but concise. Focus on what is genuinely important.", "请尽量全面，但保持简洁，只关注真正重要的内容。"),
    "",
    pickPromptText(language, "If folder context is available, use it as a hint for categorization — folder structure often reflects the user's organizational intent.", "如果能从路径或目录结构中看出分类意图，请把它当作辅助线索使用。"),
    "",
    folderContext ? `${pickPromptText(language, "## Folder Context", "## 目录上下文")}\n${folderContext}` : "",
    "",
    purpose ? `${pickPromptText(language, "## Wiki Purpose (for context)", "## Wiki 目的（上下文）")}\n${purpose}` : "",
    schema ? `${pickPromptText(language, "## Wiki Schema", "## Wiki 结构规范")}\n${schema}` : "",
    index ? `${pickPromptText(language, "## Current Wiki Index (for checking existing content)", "## 当前 Wiki 索引（用于判断现有内容）")}\n${index}` : "",
    overview ? `${pickPromptText(language, "## Current Wiki Overview", "## 当前 Wiki 概览")}\n${overview}` : "",
    "",
    `${pickPromptText(language, "## Source Path", "## 来源路径")}\n${sourcePath}`,
    "",
    pickPromptText(language, "## Source Content", "## 来源正文"),
    sourceContent,
  ].join("\n")
}

export function buildGenerationPrompt({ schema, purpose, index, overview, sourcePath, sourceContent, targetLanguage, folderContext }) {
  const language = normalizePromptLanguage(targetLanguage)
  const sourceFileName = path.basename(sourcePath)
  const sourceBaseName = sourceFileName.replace(/\.[^.]+$/, "")
  return [
    pickPromptText(language, "You are a wiki maintainer. Based on the analysis provided, generate wiki files.", "你是一个 wiki 维护者。请根据分析结果生成 wiki 文件。"),
    languageInstruction(language),
    "",
    pickPromptText(language, "## IMPORTANT: Source File", "## 关键：来源文件"),
    pickPromptText(language, `The original source file is: **${sourceFileName}**`, `原始来源文件是：**${sourceFileName}**`),
    pickPromptText(language, `All wiki pages generated from this source MUST include this filename in their frontmatter \`sources\` field.`, `所有由该来源生成的 wiki 页面，都必须在 frontmatter 的 \`sources\` 字段中包含这个原始文件名。`),
    "",
    pickPromptText(language, "## What to generate", "## 需要生成的内容"),
    "",
    pickPromptText(language, `1. A source summary page at **wiki/sources/${sourceBaseName}.md** (MUST use this exact path)`, `1. 在 **wiki/sources/${sourceBaseName}.md** 生成来源摘要页（必须使用这个精确路径）`),
    pickPromptText(language, "2. Entity pages in wiki/entities/ for key entities identified in the analysis", "2. 为分析识别出的关键实体生成 wiki/entities/ 下的实体页"),
    pickPromptText(language, "3. Concept pages in wiki/concepts/ for key concepts identified in the analysis", "3. 为分析识别出的关键概念生成 wiki/concepts/ 下的概念页"),
    pickPromptText(language, "4. An updated wiki/index.md — add new entries to existing categories, preserve all existing entries", "4. 更新 wiki/index.md —— 向现有分类中加入新条目，并保留所有已有条目"),
    pickPromptText(language, "5. An updated wiki/overview.md — a high-level summary of what the entire wiki covers, updated to reflect the newly ingested source", "5. 更新 wiki/overview.md —— 用高层总结描述整个 wiki 覆盖了什么，并反映这次新增来源"),
    pickPromptText(language, "6. Optionally create query/comparison/synthesis pages only when they are clearly justified by the source", "6. 只有在来源明确支持时，才可选生成 query/comparison/synthesis 页面"),
    "",
    pickPromptText(language, "## Frontmatter Rules (CRITICAL)", "## Frontmatter 规则（关键）"),
    "",
    pickPromptText(language, "Every page MUST have YAML frontmatter with these fields:", "每个页面都必须包含以下 YAML frontmatter 字段："),
    "```yaml",
    "---",
    "type: source | entity | concept | comparison | query | synthesis | overview",
    "title: Human-readable title",
    "created: YYYY-MM-DD",
    "updated: YYYY-MM-DD",
    "tags: []",
    "related: []",
    `sources: [\"${sourceFileName}\"]`,
    `source_path: \"${sourcePath}\"`,
    "---",
    "```",
    "",
    pickPromptText(language, `The \`sources\` field MUST always contain "${sourceFileName}" — this links the wiki page back to the original uploaded document.`, `\`sources\` 字段必须始终包含 "${sourceFileName}"，用来把 wiki 页面关联回原始上传文档。`),
    "",
    pickPromptText(language, "Other rules:", "其他规则："),
    pickPromptText(language, "- Use [[wikilink]] syntax for cross-references between pages", "- 页面之间的交叉引用使用 [[wikilink]] 语法"),
    pickPromptText(language, "- If the page title is primarily Chinese, the filename may use Chinese directly; do not transliterate it into pinyin.", "- 如果页面标题主要是中文，文件名可以直接使用中文；不要把中文标题转成拼音"),
    pickPromptText(language, "- If the page title is primarily English or mixed English terminology, continue using a kebab-case filename.", "- 如果页面标题主要是英文或混合英文术语，可以继续使用 kebab-case 文件名"),
    pickPromptText(language, "- Follow the analysis recommendations on what to emphasize", "- 以分析阶段的建议来决定应强调哪些内容"),
    pickPromptText(language, "- If the analysis found connections to existing pages, add cross-references", "- 如果分析发现与现有页面有关联，请补上交叉引用"),
    pickPromptText(language, "- Reuse the exact existing wiki slug/path when the analysis indicates an entity or concept already exists; update that page instead of inventing a near-duplicate filename", "- 如果分析表明某个实体或概念已经存在，请复用现有 wiki slug/path，更新那一页，而不是重新发明一个近似文件名"),
    pickPromptText(language, "- If the index suggests two names refer to the same entity or concept, prefer updating the best matching existing page and add aliases/cross-links in the body rather than creating another sibling page", "- 如果 index 暗示两个名称指向同一个实体或概念，优先更新最匹配的已有页面，并在正文里补别名或交叉链接，而不是新建一个兄弟页面"),
    pickPromptText(language, "- Only create a brand-new entity or concept page when the topic is genuinely distinct, not merely a paraphrase, abbreviation variant, or translation variant of an existing page", "- 只有在主题确实不同的时候，才新建实体页或概念页；不要因为换了说法、缩写或翻译方式就另起一页"),
    pickPromptText(language, "- Do not write outside wiki/", "- 不要写到 wiki/ 目录之外"),
    pickPromptText(language, "- Prefer high recall for materially important entities and concepts: if an entity or concept is central to understanding the source, create or update a dedicated page instead of only mentioning it in the source summary", "- 对真正重要的实体和概念采用高召回策略：如果它们对理解来源很关键，就应创建或更新专门页面，而不是只在来源摘要里顺带提一下"),
    pickPromptText(language, "- Do not collapse multiple important entities or concepts into a single source summary page when they deserve their own pages", "- 如果多个重要实体或概念本来就应该有独立页面，不要把它们全部压进一个来源摘要页"),
    pickPromptText(language, "- Create entity/concept pages for items that are central, repeatedly referenced, define the source's scope, or are necessary for answering likely downstream questions", "- 对于那些处于核心位置、被反复提及、定义了来源范围，或者是回答后续问题所必需的实体/概念，请生成对应页面"),
    pickPromptText(language, "- If an entity or concept already likely exists, prefer updating that existing page with new detail; do not silently omit the new information, and do not create a duplicate page unless the distinction is explicit and material", "- 如果某个实体或概念很可能已经存在，优先用新细节更新已有页面；不要静默忽略新信息，也不要在缺乏明确实质区别时新建重复页"),
    pickPromptText(language, "- It is acceptable to generate several entity and concept pages from one source when the source is dense and conceptually rich", "- 当来源本身信息密度高、概念丰富时，从一个来源生成多个实体页和概念页是合理的"),
    pickPromptText(language, "- The source summary page must preserve concrete facts, scope, caveats, and the most important supporting details from the original source", "- 来源摘要页必须保留原始来源中的具体事实、适用范围、限制条件和最重要的支撑细节"),
    pickPromptText(language, "- wiki/index.md must remain a usable navigation index, not just a dump of titles", "- wiki/index.md 必须保持为可用的导航索引，而不是标题堆积"),
    pickPromptText(language, "- wiki/overview.md should describe how the new source changes the overall project picture, not merely repeat the source summary", "- wiki/overview.md 应描述新来源如何改变整体项目图景，而不是简单重复来源摘要"),
    "",
    pickPromptText(language, "## Optional Review Blocks", "## 可选 REVIEW Blocks"),
    pickPromptText(language, "After all FILE blocks, you MAY emit REVIEW blocks for cases that need human judgment.", "在所有 FILE blocks 之后，如果存在需要人工判断的情况，你可以输出 REVIEW blocks。"),
    pickPromptText(language, "Use REVIEW blocks when the source reveals a likely duplicate, contradiction, missing dedicated page, or a meaningful follow-up suggestion.", "当来源暴露出疑似重复、冲突、缺少专门页面，或值得跟进的建议时，请使用 REVIEW blocks。"),
    pickPromptText(language, "Do NOT create trivial reviews. Only create them when they would help keep the wiki coherent.", "不要输出琐碎的 review，只有在它们确实有助于保持 wiki 一致性时才输出。"),
    "",
    pickPromptText(language, "Allowed review types:", "允许的 review 类型："),
    "- contradiction",
    "- duplicate",
    "- missing-page",
    "- suggestion",
    "",
    pickPromptText(language, "REVIEW block template:", "REVIEW block 模板："),
    "```",
    "---REVIEW: type | Title---",
    "Short description of the issue or suggestion.",
    "OPTIONS: Create Page | Skip",
    "PAGES: wiki/path/one.md, wiki/path/two.md",
    "SEARCH: query 1 | query 2 | query 3",
    "---END REVIEW---",
    "```",
    "",
    pickPromptText(language, "Use the PAGES line when specific existing or proposed wiki pages are involved.", "当某些现有或建议的 wiki 页面与该事项直接相关时，请填写 PAGES 行。"),
    pickPromptText(language, "Use the SEARCH line only for missing-page or suggestion reviews when it would help future research.", "只有在 missing-page 或 suggestion 类型、且确实有助于后续研究时，才填写 SEARCH 行。"),
    "",
    purpose ? `${pickPromptText(language, "## Wiki Purpose", "## Wiki 目的")}\n${purpose}` : "",
    schema ? `${pickPromptText(language, "## Wiki Schema", "## Wiki 结构规范")}\n${schema}` : "",
    folderContext ? `${pickPromptText(language, "## Folder Context", "## 目录上下文")}\n${folderContext}` : "",
    index ? `${pickPromptText(language, "## Current Wiki Index (preserve all existing entries, add new ones)", "## 当前 Wiki 索引（保留所有已有条目，并在相应分类中加入新条目）")}\n${index}` : "",
    overview ? `${pickPromptText(language, "## Current Overview (update this to reflect the new source)", "## 当前 Overview（需要更新以反映新来源）")}\n${overview}` : "",
    "",
    pickPromptText(language, "## Original Source Content", "## 原始来源内容"),
    sourceContent,
    "",
    pickPromptText(language, "## Output Format (MUST FOLLOW EXACTLY — this is how the parser reads your response)", "## 输出格式（必须严格遵守 —— 解析器将按此读取你的响应）"),
    "",
    pickPromptText(language, "Your ENTIRE response consists of FILE blocks, followed optionally by REVIEW blocks. Nothing else.", "你的整个响应必须由 FILE blocks 组成，之后可选追加 REVIEW blocks。不要输出别的内容。"),
    pickPromptText(language, "If REVIEW blocks are needed, place them AFTER all FILE blocks and before the response ends.", "如果需要 REVIEW blocks，请把它们放在所有 FILE blocks 之后、响应结束之前。"),
    "",
    pickPromptText(language, "FILE block template:", "FILE block 模板："),
    "```",
    "---FILE: wiki/path/to/page.md---",
    "(complete file content with YAML frontmatter)",
    "---END FILE---",
    "```",
    "",
    pickPromptText(language, "Strict output requirements:", "严格输出要求："),
    pickPromptText(language, "1. The very first characters of your response must be ---FILE:", "1. 你的响应最开头的字符必须是 ---FILE:"),
    pickPromptText(language, "2. No preamble, no explanation, no markdown fences around the whole response", "2. 不要写前言、不要解释、不要给整个响应套 markdown 代码围栏"),
    pickPromptText(language, "3. No trailing commentary after the last ---END FILE---", "3. 在最后一个 ---END FILE--- 之后，不要再写任何说明"),
    pickPromptText(language, "4. If you produce wiki/index.md or wiki/overview.md, output their full updated contents", "4. 如果你产出了 wiki/index.md 或 wiki/overview.md，请输出它们完整更新后的内容"),
    pickPromptText(language, "5. If you emit REVIEW blocks, do not place any ordinary prose outside FILE/REVIEW blocks", "5. 如果输出了 REVIEW blocks，不要在 FILE/REVIEW blocks 之外夹杂普通说明文字"),
  ].join("\n")
}
