import path from "node:path"
import { languageInstruction } from "../lib/text.js"

export function buildAnalysisPrompt({ schema, purpose, index, overview, sourcePath, sourceContent, targetLanguage }) {
  return [
    "你是一个严谨的研究分析助手。请阅读源文档，并为 LLM Wiki 流程产出结构化分析。",
    languageInstruction(targetLanguage),
    "",
    "Your analysis should cover:",
    "",
    "## Key Entities",
    "List people, organizations, products, datasets, tools mentioned. For each:",
    "- Name and type",
    "- Role in the source (central vs. peripheral)",
    "- Whether it likely already exists in the wiki",
    "",
    "## Key Concepts",
    "List theories, methods, techniques, and phenomena. For each:",
    "- Name and brief definition",
    "- Why it matters in this source",
    "- Whether it likely already exists in the wiki",
    "",
    "## Main Arguments & Findings",
    "- What are the core claims or results?",
    "- What evidence supports them?",
    "- How strong is the evidence?",
    "",
    "## Connections to Existing Wiki",
    "- What existing pages does this source relate to?",
    "- Does it strengthen, challenge, or extend existing knowledge?",
    "",
    "## Contradictions & Tensions",
    "- Does anything in this source conflict with existing wiki content?",
    "- Are there internal tensions or caveats?",
    "",
    "## Recommendations",
    "- What wiki pages should be created or updated?",
    "- What should be emphasized vs. de-emphasized?",
    "- Any open questions worth flagging for the user?",
    "",
    "Be thorough but concise. Focus on what is genuinely important.",
    "",
    purpose ? `## Wiki Purpose\n${purpose}` : "",
    schema ? `## Wiki Schema\n${schema}` : "",
    index ? `## Current Wiki Index\n${index}` : "",
    overview ? `## Current Wiki Overview\n${overview}` : "",
    "",
    `## Source Path\n${sourcePath}`,
    "",
    "## Source Content",
    sourceContent,
  ].join("\n")
}

export function buildGenerationPrompt({ schema, purpose, index, overview, sourcePath, analysis, targetLanguage }) {
  const sourceFileName = path.basename(sourcePath)
  const sourceBaseName = sourceFileName.replace(/\.[^.]+$/, "")
  return [
    "你是一个 wiki 维护者。请根据分析结果生成 wiki 文件。",
    languageInstruction(targetLanguage),
    "",
    `The original source file is: ${sourceFileName}`,
    `A source summary page MUST exist at wiki/sources/${sourceBaseName}.md`,
    "",
    "What to generate:",
    `1. A source summary page at wiki/sources/${sourceBaseName}.md`,
    "2. Entity pages in wiki/entities/ for key entities when justified",
    "3. Concept pages in wiki/concepts/ for key concepts when justified",
    "4. An updated wiki/index.md preserving existing entries and adding new ones",
    "5. An updated wiki/overview.md that reflects the new source in the overall project picture",
    "6. Optionally query/comparison/synthesis pages only when clearly warranted by the source",
    "",
    "Frontmatter rules for created pages:",
    "```yaml",
    "---",
    "type: source | entity | concept | comparison | query | synthesis | overview",
    "title: Human-readable title",
    "created: YYYY-MM-DD",
    "updated: YYYY-MM-DD",
    "tags: []",
    "related: []",
    `sources: [\"${sourceFileName}\"]`,
    "---",
    "```",
    "",
    "Other rules:",
    "- Use [[wikilink]] syntax for cross-references",
    "- 如果页面标题主要是中文，文件名可以直接使用中文；不要把中文标题转成拼音",
    "- 如果页面标题主要是英文或混合英文术语，可以继续使用 kebab-case 文件名",
    "- Preserve and extend the existing wiki structure",
    "- If analysis found links to existing pages, reflect them",
    "- Do not write outside wiki/",
    "",
    purpose ? `## Wiki Purpose\n${purpose}` : "",
    schema ? `## Wiki Schema\n${schema}` : "",
    index ? `## Current Wiki Index\n${index}` : "",
    overview ? `## Current Wiki Overview\n${overview}` : "",
    "",
    "## Stage 1 Analysis",
    analysis,
    "",
    "Output format (strict):",
    "Your entire response must consist only of FILE blocks.",
    "---FILE: wiki/path/to/file.md---",
    "(complete file content with YAML frontmatter)",
    "---END FILE---",
    "",
    "Strict output requirements:",
    "1. The very first characters of your response must be ---FILE:",
    "2. No preamble, no explanation, no markdown fences around the whole response",
    "3. No trailing commentary after the last ---END FILE---",
    "4. If you produce wiki/index.md or wiki/overview.md, output their full updated contents",
  ].join("\n")
}
